import "./style.css";import {api} from "./api";import {subscribe} from "./events";
type Machine={id:string;name:string;active:boolean};type Sim={spins:number;rtp:number;hitFrequency:number;averageWin:number;maxWin:number;freeSpinTriggers:number};
const root=document.querySelector("#app")!;let machines:Machine[]=[];let selected="";let unsub:(()=>void)|null=null;let sim:Sim|null=null;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
async function load(){const d=await api<{machines:Machine[]}>("/slot-api/machines");machines=d.machines;if(!selected&&machines[0])selected=machines[0].id;render()}
function render(){const m=machines.find(x=>x.id===selected);root.innerHTML=`<main><header><h1>🎰 Slot Configurator</h1><button id="refresh">Refresh</button>${m?'<button id="activate">'+(m.active?"● Server Active":"Activate Slot Server")+"</button>":""}</header><section class="card"><b>Machines</b><div class="machines">${machines.map(x=>`<button class="${x.id===selected?"selected":""}" data-machine="${x.id}">${esc(x.name)} ${x.active?"●":""}</button>`).join("")}</div></section>${m?content(m):'<section class="card">No machines.</section>'}</main>`;document.querySelector("#refresh")?.addEventListener("click",load);document.querySelectorAll("[data-machine]").forEach(x=>x.addEventListener("click",()=>{selected=(x as HTMLElement).dataset.machine!;unsub?.();sim=null;render()}));document.querySelector("#activate")?.addEventListener("click",activate);document.querySelector("#subscribe")?.addEventListener("click",()=>{unsub?.();unsub=subscribe(selected,e=>{const el=document.querySelector("#liveWin");if(el)el.textContent=`Win: ${e.win} | Scatter: ${e.scatter}`})});document.querySelector("#simulate")?.addEventListener("click",runSim)}
function content(m:Machine){return `<section class="card"><h2>⚡ Server Result Emitter</h2><p>Machine: ${esc(m.name)}</p><pre>const eventSource = new EventSource("/slot-api/machines/${m.id}/events");
eventSource.addEventListener("spin", event => {
  const result = JSON.parse(event.data);
  console.log("SPIN RESULT:", result);
});</pre><button id="subscribe" ${m.active?"":"disabled"}>Subscribe to Events</button> <b id="liveWin"></b></section><section class="card"><h2>📊 Simulation</h2><label>Spins <input id="spins" type="number" min="1000" max="10000000" step="1000" value="100000"></label> <button id="simulate">Run Simulation</button>${sim?`<div class="metrics"><div>RTP <b>${(sim.rtp*100).toFixed(3)}%</b></div><div>Hit <b>${(sim.hitFrequency*100).toFixed(2)}%</b></div><div>Average Win <b>${sim.averageWin.toFixed(3)}</b></div><div>Max Win <b>${sim.maxWin.toFixed(2)}</b></div><div>Free Spins <b>${sim.freeSpinTriggers}</b></div></div>`:""}</section>`}
async function activate(){await api(`/slot-api/machines/${selected}/activate`,{method:"POST"});machines=machines.map(x=>x.id===selected?{...x,active:true}:x);render()}
async function runSim(){const n=Number((document.querySelector("#spins") as HTMLInputElement).value)||100000;sim=await api<Sim>(`/slot-api/machines/${selected}/simulate`,{method:"POST",body:JSON.stringify({spins:n})});render()}
load().catch(e=>root.innerHTML=`<main><section class="card">Error: ${esc(e.message)}</section></main>`);