"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {defaultSlot} from "@/lib/slot/default";
import {Reel,SlotConfig} from "@/lib/slot/types";
const clone=<T,>(v:T):T=>structuredClone(v);
type Machine={id:string;name:string;updatedAt:string};

export default function Home(){
 const router=useRouter();
 const[c,setC]=useState<SlotConfig>(()=>clone(defaultSlot));
 const[m,setM]=useState<any>(null),[s,setS]=useState<any>(null),[spins,setSpins]=useState(100000);
 const[busy,setBusy]=useState(false),[user,setUser]=useState<any>(null),[authChecking,setAuthChecking]=useState(true),[simOpen,setSimOpen]=useState(true);
 const[saveState,setSaveState]=useState<"loading"|"saved"|"saving"|"error">("loading");
 const[theme,setTheme]=useState<"dark"|"red">("dark");
 const[machines,setMachines]=useState<Machine[]>([]),[machineId,setMachineId]=useState(""),[machineName,setMachineName]=useState(""),[machineBusy,setMachineBusy]=useState(false),[serverActive,setServerActive]=useState(false);
 const payCounts=useMemo(()=>{const x=new Set<string>();Object.values(c.paytable).forEach(p=>Object.keys(p).forEach(n=>x.add(n)));return[...x].sort((a,b)=>Number(a)-Number(b))},[c.paytable]);

 useEffect(()=>{let alive=true;(async()=>{try{const ar=await fetch("/api/auth/me");if(!ar.ok){router.replace("/login");return}const authData=await ar.json();setUser(authData.user);const r=await fetch("/slot-api/machines");if(!r.ok)throw new Error("load");const d=await r.json();if(alive){setMachines(d.machines||[]);setMachineId(d.activeId||"");setMachineName(d.config?.name||"");if(d.config)setC(clone(d.config));setServerActive(Boolean(d.active));setSaveState("saved");setAuthChecking(false)}}catch{if(alive){setSaveState("error");setAuthChecking(false)}}})();return()=>{alive=false}},[router]);

 useEffect(()=>{if(authChecking||!machineId)return;setSaveState("saving");const t=setTimeout(async()=>{try{const config={...c,name:machineName||c.name};const r=await fetch("/slot-api/machines/"+encodeURIComponent(machineId),{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({id:machineId,name:config.name,config})});const d=await r.json().catch(()=>({}));if(r.status===401){router.replace("/login");return}if(!r.ok){console.error("Machine save failed:",d);setSaveState("error");return}setMachines(x=>x.map(v=>v.id===machineId?{...v,name:config.name,updatedAt:d.updatedAt}:v));setSaveState("saved")}catch(e){console.error(e);setSaveState("error")}},500);return()=>clearTimeout(t)},[c,machineId,machineName,authChecking,router]);

 if(authChecking)return <main><p className="muted">Checking session...</p></main>;
 function patch(p:Partial<SlotConfig>){setC(v=>({...v,...p}));setM(null);setS(null)}
 function updateReel(i:number,r:Reel){patch({reels:c.reels.map((x,n)=>n===i?r:x)})}
 function addReel(){patch({reels:[...c.reels,{id:"R"+(c.reels.length+1),strip:[c.symbols[0]?.id||"A"]}]})}
 function deleteReel(i:number){if(c.reels.length>1)patch({reels:c.reels.filter((_,n)=>n!==i)})}
 function addField(i:number){const r=c.reels[i];updateReel(i,{...r,strip:[...r.strip,c.symbols[0]?.id||"A"]})}
 function deleteField(ri:number,fi:number){const r=c.reels[ri];if(r.strip.length>1)updateReel(ri,{...r,strip:r.strip.filter((_,n)=>n!==fi)})}
 function setField(ri:number,fi:number,v:string){const r=c.reels[ri],strip=[...r.strip];strip[fi]=v;updateReel(ri,{...r,strip})}
 function addSymbol(){const id="SYM"+(c.symbols.length+1);patch({symbols:[...c.symbols,{id,name:"🎰",type:"normal"}],reels:c.reels.map(r=>({...r,strip:[...r.strip,id]})),paytable:{...c.paytable,[id]:{}}})}
 function updatePayout(symbol:string,count:string,value:number){patch({paytable:{...c.paytable,[symbol]:{...c.paytable[symbol],[count]:value}}})}
 function addPayoutCount(n:number){patch({paytable:Object.fromEntries(Object.entries(c.paytable).map(([x,p])=>[x,{...p,[n]:0}]))})}
 function removePayoutCount(n:string){if(payCounts.length<=2||(n!==payCounts[0]&&n!==payCounts[payCounts.length-1]))return;patch({paytable:Object.fromEntries(Object.entries(c.paytable).map(([x,p])=>{const q={...p};delete q[n];return[x,q]}))})}
 async function selectMachine(id:string){const r=await fetch("/slot-api/machines/"+encodeURIComponent(id));if(!r.ok)return;const d=await r.json();setMachineId(id);setMachineName(d.config?.name||"");if(d.config)setC(clone(d.config));setServerActive(Boolean(d.active));setM(null);setS(null);setSaveState("saved")}
 async function newMachine(){const name=prompt("New slot machine name","New Slot Machine");if(!name)return;setMachineBusy(true);try{const r=await fetch("/slot-api/machines",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Create failed");setMachines(x=>[d.machine,...x]);setMachineId(d.machine.id);setMachineName(d.machine.name);setC(clone(d.config));setSaveState("saved")}catch(e){console.error(e);setSaveState("error")}finally{setMachineBusy(false)}}
 async function activateServer(){const r=await fetch("/slot-api/machines/"+encodeURIComponent(machineId)+"/activate",{method:"POST"});if(r.ok)setServerActive(true)}
 function eventSubscribeCode(){return `const eventSource = new EventSource("/slot-api/machines/${machineId}/events");
eventSource.addEventListener("spin", (event) => {
  const result = JSON.parse(event.data);
  console.log("SPIN RESULT:", result);

  // Example:
  // document.querySelector("#winLabel").textContent = result.win;
});

eventSource.onerror = (error) => console.error("Slot events:", error);
// eventSource.close(); // unsubscribe`}
 function copyEventCode(){navigator.clipboard?.writeText(eventSubscribeCode())}
 async function deleteMachine(){if(machines.length<=1||!confirm("Delete this slot machine?"))return;setMachineBusy(true);try{const r=await fetch("/slot-api/machines/"+encodeURIComponent(machineId),{method:"DELETE"});if(!r.ok)throw new Error("Delete failed");const remaining=machines.filter(x=>x.id!==machineId);setMachines(remaining);await selectMachine(remaining[0].id)}catch(e){console.error(e);setSaveState("error")}finally{setMachineBusy(false)}}
 async function calc(){setBusy(true);try{const r=await fetch("/slot-api/math",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(c)});if(r.status===401)return router.replace("/login");setM(await r.json())}finally{setBusy(false)}}
 async function sim(){setBusy(true);try{const r=await fetch("/slot-api/machines/"+encodeURIComponent(machineId)+"/simulate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({config:c,spins})});if(r.status===401)return router.replace("/login");setS(await r.json())}finally{setBusy(false)}}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/login")}

 return <div className={`appShell theme-${theme}`}>
  <header className="topbar"><div className="brand"><b>Slot Simulator</b><span>{user?.role==="admin"?"Admin":"User"} · {user?.email} · {saveState==="saving"?"Saving...":saveState==="saved"?"Saved":"Save error"}</span></div><div className="topActions"><div className="themeSwitch"><button className={theme==="dark"?"active":""} onClick={()=>setTheme("dark")}>Dark</button><button className={theme==="red"?"active":""} onClick={()=>setTheme("red")}>Red</button></div><button onClick={logout}>Logout</button></div></header>
  <div className="machineBar"><div className="machineSelect"><strong>Slot Machines</strong><select value={machineId} onChange={e=>selectMachine(e.target.value)}>{machines.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="machineActions"><input value={machineName} onChange={e=>{setMachineName(e.target.value);setC(v=>({...v,name:e.target.value}))}}/>{user?.role==="admin"&&<><button onClick={activateServer} disabled={serverActive||machineBusy}>{serverActive?"● Server Active":"Activate Slot Server"}</button><button onClick={newMachine} disabled={machineBusy}>+ New Machine</button><button className="danger" onClick={deleteMachine} disabled={machines.length<=1||machineBusy}>Delete</button></>}</div></div>
  <main className="workspace"><div className="editor">
   <section className="panel compact"><div className="sectionTitle"><h1>Machine Configuration</h1><button onClick={calc} disabled={busy}>Calculate RTP</button></div><div className="fields"><label>Machine name<input value={c.name} onChange={e=>patch({name:e.target.value})}/></label><label>Target RTP %<input type="number" step=".01" value={c.targetRtp*100} onChange={e=>patch({targetRtp:Number(e.target.value)/100})}/></label><label>Bet per spin<input type="number" step=".01" value={c.betPerSpin} onChange={e=>patch({betPerSpin:Number(e.target.value)})}/></label></div></section>
   <section className="panel compact"><div className="sectionTitle"><h2>Reel Strips <small>{c.reels.length} reels</small></h2><button onClick={addReel}>+ Reel</button></div><div className="reels dynamicReels">{c.reels.map((r,ri)=><div className="reel" key={r.id}><div className="reelHeader"><strong>{r.id}</strong><button className="danger small" onClick={()=>deleteReel(ri)} disabled={c.reels.length<=1}>Delete</button></div>{r.strip.map((f,fi)=><div className="reelField" key={fi}><input value={f} onChange={e=>setField(ri,fi,e.target.value)}/><button className="danger tiny" onClick={()=>deleteField(ri,fi)} disabled={r.strip.length<=1}>×</button></div>)}<button className="small addField" onClick={()=>addField(ri)}>+ Field</button></div>)}</div></section>
   <section className="panel compact"><div className="sectionTitle"><h2>Symbols</h2><button onClick={addSymbol}>+ Symbol</button></div><div className="symbolEditor">{c.symbols.map((sym,i)=><div className="symbolRow" key={sym.id}><input value={sym.id} onChange={e=>{const a=[...c.symbols];a[i]={...sym,id:e.target.value};patch({symbols:a})}}/><input value={sym.name} onChange={e=>{const a=[...c.symbols];a[i]={...sym,name:e.target.value};patch({symbols:a})}}/><select value={sym.type} onChange={e=>{const a=[...c.symbols];a[i]={...sym,type:e.target.value as any};patch({symbols:a})}}><option value="normal">Normal</option><option value="wild">Wild</option><option value="scatter">Scatter</option></select></div>)}</div></section>
   <section className="panel compact"><div className="sectionTitle"><h2>Paytable</h2><div className="payoutControls"><PayoutPicker payCounts={payCounts} onAdd={addPayoutCount}/><select aria-label="Remove edge payout" defaultValue="" onChange={e=>{if(e.target.value){removePayoutCount(e.target.value);e.target.value=""}}}><option value="" disabled>Remove edge…</option>{payCounts.length>2&&<><option value={payCounts[0]}>{payCounts[0]}x · low edge</option><option value={payCounts[payCounts.length-1]}>{payCounts[payCounts.length-1]}x · high edge</option></>}</select></div></div><div className="tableWrap"><table><thead><tr><th>Symbol</th>{payCounts.map(n=><th key={n}>{n}x {payCounts.length>2&&(n===payCounts[0]||n===payCounts[payCounts.length-1])&&<button className="tiny danger" title="Remove edge payout" onClick={()=>removePayoutCount(n)}>×</button>}</th>)}</tr></thead><tbody>{c.symbols.map(sym=><tr key={sym.id}><td>{sym.name}</td>{payCounts.map(n=><td key={n}><input className="payInput" type="number" min="0" step=".01" value={c.paytable[sym.id]?.[n]??0} onChange={e=>updatePayout(sym.id,n,Number(e.target.value))}/></td>)}</tr>)}</tbody></table></div></section>
   <section className="panel compact"><div className="sectionTitle"><h2>Free Spins</h2><label className="check"><input type="checkbox" checked={c.freeSpins.enabled} onChange={e=>patch({freeSpins:{...c.freeSpins,enabled:e.target.checked}})}/> Enabled</label></div><div className="fields featureFields"><label>Trigger symbol<select value={c.freeSpins.triggerSymbol} onChange={e=>patch({freeSpins:{...c.freeSpins,triggerSymbol:e.target.value}})}>{c.symbols.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Trigger count<input type="number" min="1" value={c.freeSpins.triggerCount} onChange={e=>patch({freeSpins:{...c.freeSpins,triggerCount:Number(e.target.value)}})}/></label><label>Spins awarded<input type="number" min="0" value={c.freeSpins.spinsAwarded} onChange={e=>patch({freeSpins:{...c.freeSpins,spinsAwarded:Number(e.target.value)}})}/></label><label>Multiplier<input type="number" min="0" step=".1" value={c.freeSpins.multiplier} onChange={e=>patch({freeSpins:{...c.freeSpins,multiplier:Number(e.target.value)}})}/></label><label className="check"><input type="checkbox" checked={c.freeSpins.retrigger} onChange={e=>patch({freeSpins:{...c.freeSpins,retrigger:e.target.checked}})}/> Retrigger</label></div></section>
   {m&&<section className="panel compact"><h2>Theoretical Math</h2><div className="metrics"><Metric t="Target RTP" v={(c.targetRtp*100).toFixed(3)+"%"}/><Metric t="Calculated RTP" v={(m.theoreticalRtp*100).toFixed(3)+"%"}/><Metric t="Base RTP" v={(m.baseRtp*100).toFixed(3)+"%"}/><Metric t="Feature RTP" v={(m.featureRtp*100).toFixed(3)+"%"}/></div></section>}
  </div>
  <aside className={`simRail ${simOpen?"open":""}`}><button className="railToggle" onClick={()=>setSimOpen(!simOpen)}>{simOpen?"›":"‹"}<span>Simulation</span></button>{simOpen&&<div className="simContent"><div className="simHead"><h2>Simulation</h2><span>Backend</span></div><label>Number of spins<input type="number" min="1000" max="10000000" step="1000" value={spins} onChange={e=>setSpins(Number(e.target.value)||1000)}/></label><button className="runButton" onClick={sim} disabled={busy}>{busy?"Running...":"Run Simulation"}</button>{s&&<div className="simResult"><Metric t="Observed RTP" v={(s.rtp*100).toFixed(3)+"%"}/><Metric t="Target difference" v={((s.rtp-c.targetRtp)*100).toFixed(3)+"%"}/><Metric t="Hit Frequency" v={(s.hitFrequency*100).toFixed(2)+"%"}/><Metric t="Average Win" v={s.averageWin.toFixed(3)}/><Metric t="Max Win" v={s.maxWin.toFixed(2)}/><Metric t="Free Spin Triggers" v={String(s.freeSpinTriggers)}/></div>}</div>}</aside>
 </main></div>
}
function PayoutPicker({payCounts,onAdd}:{payCounts:string[];onAdd:(n:number)=>void}){const [open,setOpen]=useState(false);const [selected,setSelected]=useState("");const used=new Set(payCounts.map(Number));const options=Array.from({length:9},(_,i)=>i+1).filter(n=>!used.has(n));return <div className="payoutPicker"><button type="button" onClick={()=>setOpen(v=>!v)}>+ Payout Count ▾</button>{open&&<div className="payoutPopup addPayoutPopup">{options.length?<><select aria-label="Choose payout count" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose count…</option>{options.map(n=><option key={n} value={n}>{n}x</option>)}</select><button type="button" disabled={!selected} onClick={()=>{onAdd(Number(selected));setSelected("");setOpen(false)}}>Add</button></>:<span>1x–9x already used</span>}</div>}</div>}

function Metric({t,v}:{t:string;v:string}){return <div className="metric"><small>{t}</small><strong>{v}</strong></div>}